permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
name:         Aditya Kumar 
description:  Compilers, Software Performance optimizations
url:          https://hiraditya.github.io
enforce_ssl:  hiraditya.github.io
author:
  name: Aditya Kumar
  twitter: hiraditya
timezone: America/Los_Angeles
